version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: micro
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-ms1
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql_data: